### ISSUE TITLE
Invalid test gets generated in pycharm for functions without any contracts specified

### ISSUE THREAD

**Issue by ProLoD** [mristin/icontract-hypothesis#29]
This issue occurs when using the pycharm-plugin for a function _without any contracts_. When using the CLI-tool, this problem does not arise.

While the inferred strategy (obtained by calling ``` inspect strategy for add ```) is correct, this strategy is not used in the generated test.
Instead, a strategy that is incorrectly formatted and is not executable is generated when calling ```ghostwrite explicit ... to STDOUT ```

![afbeelding](https://user-images.githubusercontent.com/16407582/107924124-c0691880-6f72-11eb-8ef4-62993e5609a7.png)

**Comment by mristin** [comment]
Thanks a lot, @ProLoD! I'll release a patch version now as this is quite a grave bug.
